# Monitoramento
# shared_preload_libraries = 'pg_stat_statements, pg_audit'
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = 'all'
pg_stat_statements.max = 10000
# pg_audit.log = 'write, ddl, role'

# Performance
shared_buffers = 4GB
effective_cache_size = 12GB
work_mem = 16MB